language: python
cache: pip
matrix:
  include:
  - python: 3.4
    env: TOX_ENV=py34
  - python: 3.5
    env: TOX_ENV=py35
  - python: 3.4
    env: TOX_ENV=py3pep8
install:
- pip install -r requirements.txt
- pip install -r dev-requirements.txt
script:
- tox -e $TOX_ENV -- $TOX_FLAGS
after_success:
- coveralls

